### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by black5ky99** [ulnk/strife#1]
**Describe the bug**
Module not found while compiling.

**♻ To Reproduce**
1. Clone Repo
2. Install dependencies
3. Start Client

**🧯 Expected behavior**
That the Client is starting.

**🎥 Screenshots or Videos**
![image](https://user-images.githubusercontent.com/55916821/142605060-c1bb1ab9-9ad4-4b21-a048-3962f47d1b75.png)

**Comment by ulnk** [comment]
👍 Thank you for the bug.

In the next push I will fix this issue.

**Comment by ulnk** [comment]
I forgot to commit the Modal folder. Currently I am away.
